create table author (id bigint not null, author_first_name varchar(255), author_introduction varchar(255), author_last_name varchar(255), author_nationality varchar(255), primary key (id)) engine=InnoDB;
create table book (book_id bigint not null, author_full_name varchar(255), book_genre varchar(255), bookisbn varchar(255), book_lang varchar(255), book_pages integer not null, book_price double precision not null, book_publisher varchar(255), book_title varchar(255), book_website varchar(255), author_id bigint not null, primary key (book_id)) engine=InnoDB;
create table hibernate_sequence (next_val bigint) engine=InnoDB;
insert into hibernate_sequence values ( 1 );
create table library (id varchar(255) not null, author varchar(255), book_name varchar(255), book_shelf integer, isbn varchar(255), primary key (id)) engine=InnoDB;
alter table book add constraint FKklnrv3weler2ftkweewlky958 foreign key (author_id) references author (id);
create table author (id bigint not null, author_first_name varchar(255), author_introduction varchar(255), author_last_name varchar(255), author_nationality varchar(255), primary key (id)) engine=InnoDB;
create table book (book_id bigint not null, author_full_name varchar(255), book_genre varchar(255), bookisbn varchar(255), book_lang varchar(255), book_pages integer not null, book_price double precision not null, book_publisher varchar(255), book_title varchar(255), book_website varchar(255), author_id bigint not null, primary key (book_id)) engine=InnoDB;
create table hibernate_sequence (next_val bigint) engine=InnoDB;
insert into hibernate_sequence values ( 1 );
create table library (id varchar(255) not null, author varchar(255), book_name varchar(255), book_shelf integer, isbn varchar(255), primary key (id)) engine=InnoDB;
alter table book add constraint FKklnrv3weler2ftkweewlky958 foreign key (author_id) references author (id);
create table author (id bigint not null, author_first_name varchar(255), author_introduction varchar(255), author_last_name varchar(255), author_nationality varchar(255), primary key (id)) engine=InnoDB;
create table book (book_id bigint not null, author_full_name varchar(255), book_genre varchar(255), bookisbn varchar(255), book_lang varchar(255), book_pages integer not null, book_price double precision not null, book_publisher varchar(255), book_title varchar(255), book_website varchar(255), author_id bigint not null, primary key (book_id)) engine=InnoDB;
create table hibernate_sequence (next_val bigint) engine=InnoDB;
insert into hibernate_sequence values ( 1 );
create table library (id varchar(255) not null, author varchar(255), book_name varchar(255), book_shelf integer, isbn varchar(255), primary key (id)) engine=InnoDB;
alter table book add constraint FKklnrv3weler2ftkweewlky958 foreign key (author_id) references author (id);
create table author (id bigint not null, author_first_name varchar(255), author_introduction varchar(255), author_last_name varchar(255), author_nationality varchar(255), primary key (id)) engine=InnoDB;
create table book (book_id bigint not null, author_full_name varchar(255), book_genre varchar(255), bookisbn varchar(255), book_lang varchar(255), book_pages integer not null, book_price double precision not null, book_publisher varchar(255), book_title varchar(255), book_website varchar(255), author_id bigint not null, primary key (book_id)) engine=InnoDB;
create table hibernate_sequence (next_val bigint) engine=InnoDB;
insert into hibernate_sequence values ( 1 );
create table library (id varchar(255) not null, author varchar(255), book_name varchar(255), book_shelf integer, isbn varchar(255), primary key (id)) engine=InnoDB;
alter table book add constraint FKklnrv3weler2ftkweewlky958 foreign key (author_id) references author (id);
create table author (id bigint not null, author_first_name varchar(255), author_introduction varchar(255), author_last_name varchar(255), author_nationality varchar(255), primary key (id)) engine=InnoDB;
create table book (book_id bigint not null, author_full_name varchar(255), book_genre varchar(255), bookisbn varchar(255), book_lang varchar(255), book_pages integer not null, book_price double precision not null, book_publisher varchar(255), book_title varchar(255), book_website varchar(255), author_id bigint not null, primary key (book_id)) engine=InnoDB;
create table hibernate_sequence (next_val bigint) engine=InnoDB;
insert into hibernate_sequence values ( 1 );
create table library (id varchar(255) not null, author varchar(255), book_name varchar(255), book_shelf integer, isbn varchar(255), primary key (id)) engine=InnoDB;
alter table book add constraint FKklnrv3weler2ftkweewlky958 foreign key (author_id) references author (id);
create table author (id bigint not null, author_first_name varchar(255), author_introduction varchar(255), author_last_name varchar(255), author_nationality varchar(255), primary key (id)) engine=InnoDB;
create table book (book_id bigint not null, author_full_name varchar(255), book_genre varchar(255), bookisbn varchar(255), book_lang varchar(255), book_pages integer not null, book_price double precision not null, book_publisher varchar(255), book_title varchar(255), book_website varchar(255), author_id bigint, primary key (book_id)) engine=InnoDB;
create table hibernate_sequence (next_val bigint) engine=InnoDB;
insert into hibernate_sequence values ( 1 );
create table library (id varchar(255) not null, author varchar(255), book_name varchar(255), book_shelf integer, isbn varchar(255), primary key (id)) engine=InnoDB;
alter table book add constraint FKklnrv3weler2ftkweewlky958 foreign key (author_id) references author (id);
create table author (id bigint not null, author_first_name varchar(255), author_introduction varchar(255), author_last_name varchar(255), author_nationality varchar(255), primary key (id)) engine=InnoDB;
create table book (book_id bigint not null, author_full_name varchar(255), book_genre varchar(255), bookisbn varchar(255), book_lang varchar(255), book_pages integer not null, book_price double precision not null, book_publisher varchar(255), book_title varchar(255), book_website varchar(255), author_id bigint, primary key (book_id)) engine=InnoDB;
create table hibernate_sequence (next_val bigint) engine=InnoDB;
insert into hibernate_sequence values ( 1 );
create table library (id varchar(255) not null, author varchar(255), book_name varchar(255), book_shelf integer, isbn varchar(255), primary key (id)) engine=InnoDB;
alter table book add constraint FKklnrv3weler2ftkweewlky958 foreign key (author_id) references author (id);
create table author (id bigint not null, author_first_name varchar(255), author_introduction varchar(255), author_last_name varchar(255), author_nationality varchar(255), primary key (id)) engine=InnoDB;
create table book (book_id bigint not null, author_full_name varchar(255), book_genre varchar(255), bookisbn varchar(255), book_lang varchar(255), book_pages integer not null, book_price double precision not null, book_publisher varchar(255), book_title varchar(255), book_website varchar(255), author_id bigint, primary key (book_id)) engine=InnoDB;
create table hibernate_sequence (next_val bigint) engine=InnoDB;
insert into hibernate_sequence values ( 1 );
create table library (id varchar(255) not null, author varchar(255), book_name varchar(255), book_shelf integer, isbn varchar(255), primary key (id)) engine=InnoDB;
alter table book add constraint FKklnrv3weler2ftkweewlky958 foreign key (author_id) references author (id);
